services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: athenamind-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3001}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - athenamind-network

  dev:
    image: oven/bun:1-alpine
    container_name: athenamind-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3001}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    command: sh -c "bun install && bun run dev"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - athenamind-network

  postgres:
    image: postgres:16-alpine
    container_name: athenamind-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-athenamind}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - athenamind-network

volumes:
  postgres_data:

networks:
  athenamind-network:
    driver: bridge
